name: Continuous Integration
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1
    - run: |
        composer install --optimize-autoloader
    - run: |
        composer validate --no-check-all --strict
    - run: |
        npm run lint:php
    - run: |
        npm run lint:scripts
    - run: |
        npm run lint:styles
