name: Continuous Integration Tests
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Validation Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1
    - run: |
        composer install --no-dev --optimize-autoloader
    - run: |
        composer validate --no-check-all --strict
#     - run: |
#         npm run lint:php
    - uses: chekalsky/phpcs-action@v1
#       with:
#         phpcs_bin_path: './vendor/bin/phpcs'
    - run: |
        npm run lint:scripts
    - run: |
        npm run lint:styles
