# GitHub Action: whenever creating a new release of the source code,
# also create a release of the installable plugin.
# Steps to execute:
# - Checkout the source code
# - Run "composer install" to download all Composer dependencies under vendor/
# - Run "npm install" to download all npm dependencies under node_modules/
# - Build project using internal build process
# - Create a .zip file, excluding hidden and build-process files
# - Upload the .zip file as an artifact to the action (this results in a double-zipped file)
# - Upload the .zip file as a release, for download
name: Generate Installable Theme and Upload as Release Asset
on:
  release:
    types: [published]
jobs:
  build:
    name: Upload Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Composer deps
      run: |
        composer install --no-dev --optimize-autoloader
    - name: Install npm deps
      uses: bahmutov/npm-install@v1.1.0
    - name: Build project
      run: |
        npm run build
    - name: Create build folder
      run: |
        mkdir build
    - name: Create zip
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -X -r build/garrick.zip ./garrick -x .* node_modules/\* readme.md composer.* package*.* webpack.* dist/spritemap.* build**
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: garrick
        path: build/garrick.zip
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: build/garrick.zip application/zip
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
