# This is a basic workflow that is manually triggered

name: Manual workflow

on: [workflow_dispatch]

jobs:
  build:
    name: Upload Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Composer deps
      run: |
        composer install --no-dev --optimize-autoloader
    - name: Install npm deps
      uses: bahmutov/npm-install@v1.1.0
    - name: Build project
      run: |
        npm run build
    - name: Create build folder
      run: |
        mkdir build
    - name: Create zip
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -X -r build/garrick.zip ./garrick -x .* node_modules/\* readme.md composer.* package*.* webpack.* dist/spritemap.* build**
        # args: *.git* node_modules/\* .* "*/\.*" CODE_OF_CONDUCT.md CONTRIBUTING.md ISSUE_TEMPLATE.md PULL_REQUEST_TEMPLATE.md *.dist composer.* dev-helpers** build**
#    - name: Upload artifact
#      uses: actions/upload-artifact@v2
#      with:
#        name: garrick
#        path: garrick
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: build/garrick.zip application/zip
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
