# This is a basic workflow that is manually triggered

name: Manual workflow

on: [workflow_dispatch]

jobs:
  build:
    name: Upload Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Composer deps
      run: |
        composer install --no-dev --optimize-autoloader
    - name: Install npm deps
      uses: bahmutov/npm-install@v1.1.0
    - name: Build project
      run: |
        npm run build
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: garrick
        path: build/garrick.zip
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: build/garrick.zip application/zip
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
